export const LIFTER_DATA_ADDED = 'events.LIFTER_DATA_ADDED';
export const RANKING_RETRIEVED = 'events.RANKING_RETRIEVED';
export const RANKING_RETRIEVE_ERROR = 'events.RANKING_RETRIEVE_ERROR';
export const RANKING_NOT_FOUND = 'events.RANKING_NOT_FOUND';
export const RANKING_REQUEST_STARTED = 'events.RANKING_REQUEST_STARTED';